### ISSUE TITLE
NamingConventionError: Layer name is too long for the grid naming convention.

### ISSUE THREAD

**Issue by AMRIABDELLAH** [acroucher/PyTOUGH#26]
Hello Everyone, hi Acroucher !
Thanks again for your tools it's realy helped me ! i want to generate a mesh with 16 000 element but the probleme is at naming the cells ! can you please propose a solution !
Thank you !

**Comment by acroucher** [comment]
hi, which naming convention are you using for your mesh? The default is to use two digits for the layer name (see Appendix A.4 in the PyTOUGH user guide). If you need more than 99 layers then you may need to use one of the other two naming conventions, which use characters rather than digits for the layer names.

This should solve the problem, unless you also have a lot of columns in your mesh (e.g. more than 1000 with naming convention 2).

**Comment by AMRIABDELLAH** [comment]
Thank you acroucher ! That fixes my issue !
