### ISSUE TITLE
MULGraph grid to TOUGH2 grid fails due to deleted columns in 1.5.4

### ISSUE THREAD

**Issue by matthiaskardel** [acroucher/PyTOUGH#27]
When [deleting a column of a MULGraph Grid](https://github.com/acroucher/PyTOUGH/blob/master/mulgrids.py#L985) the [conversion into a TOUGH2 Grid](https://github.com/acroucher/PyTOUGH/blob/master/t2grids.py#L341) fails.
This is due to a call in `t2grids.add_underground_blocks`, which references potentially deleted columns, [here](https://github.com/acroucher/PyTOUGH/blob/master/t2grids.py#L376).

A possible workaround is a continue the for loop in `add_underground_blocks` on a KeyError exception, yet not very elegant.

Reproduction:
1. Have a mulgrid
2. Delete column on mulgrid
3. Convert mulgrid to t2 grid `t2grids.t2grid().fromgeo(mulgrid)`

**Comment by acroucher** [comment]
If you are doing any low-level surgery on your mulgrid geometry, like adding or deleting individual columns, you will need to rebuild the global lists of blocks and connections before converting to a t2grid.

This is not done automatically in methods like mulgrid.delete_column(), because rebuilding these global lists is expensive - so it would slow your code down significantly if you were adding or deleting a lot of columns. For that reason, users of low-level methods need to rebuild them explicitly,

You just need to call these two methods after your column deletion code (if your mulgrid is called `geo`):

```
geo.setup_block_name_index()
geo.setup_block_connection_name_index()
```

**Comment by matthiaskardel** [comment]
Thank you for the quick answer!

**Comment by acroucher** [comment]
Does that resolve your problem?

**Comment by matthiaskardel** [comment]
Yes, thanks!
