### ISSUE TITLE
A problem when i running the first example

### ISSUE THREAD

**Issue by Terzay** [acroucher/PyTOUGH#31]
Hi Adrian:
   I am a newcomer to PyTOUGH .When I tried to run the first example (https://github.com/acroucher/PyTOUGH/wiki/Horizontal-1D-model) ,it shown:
runfile('D:/Anaconda/spyder-dic/IDex.py', wdir='D:/Anaconda/spyder-dic')
Traceback (most recent call last):

  File "D:\Anaconda\spyder-dic\IDex.py", line 71, in <module>
    lst = t2listing('horiz1D.listing')

  File "D:\Anaconda\Anaconda3\lib\site-packages\t2listing.py", line 188, in __init__
    raise Exception('No full results found in listing file.')

Exception: No full results found in listing file.

what's wrong with it and how can i solve it?

**Comment by acroucher** [comment]
The most likely problem is that the ``dat.run()`` command failed, so that your output listing file has got no results in it.

Did you open the listing file (if it exists at all) and have a look to see if it ran?

If it didn't, you need to check if you can run ``t2eos1`` on your machine. You will need to have the TOUGH2 EOS1 executable installed on your machine and accessible from your run directory (e.g. on your system path). If you are running on Windows then the executable may be called ``t2eos1.exe`` or similar, and you will need to edit the simulator in the ``dat.run()`` command so it matches the exact name of your TOUGH2 executable.
