### ISSUE TITLE
Issues when importing a 2_D gmsh mesh into a geometry object

### ISSUE THREAD

**Issue by uqzhaozicheng** [acroucher/PyTOUGH#33]
Hi Adrian,

Recently I have been trying to use gmsh to construct the the domain of a 2D hydrological model. When I run the following code:
**geo = mulgrid().from_gmsh(filename='XXX.gmsh', layers=[1.0, 1.2])**
I came across the following error:
![image](https://user-images.githubusercontent.com/52191275/145160754-53233196-38b8-4357-955b-941bc260b90b.png)

I think there might be an error in mulgrids.py line 1657. 
![image](https://user-images.githubusercontent.com/52191275/145161163-739be5d6-097b-49d9-9d1e-3ec7bb763c13.png)

When you look at the definition of this method in line 1597, there are 5 arguments; whereas there are only 4 in line 1657. I think when executing line 1657, the parameter [spaces], which is a bool value, is mistakenly identified as the [chars].  
![image](https://user-images.githubusercontent.com/52191275/145161246-e2c549fe-e8f1-418e-8418-4731ce44ff0e.png)
Error disappeared when I specified chars=ascii_lowercase in line 1657.

**Comment by acroucher** [comment]
Thanks, I think I have fixed this now - on the 'testing' branch. The problem was that the 'justify' parameter to from_gmsh() was missing. This is then passed in to add_layers() - it was missing from that too.

I have added a unit test for from_gmsh() and it is passing now. Can you please test it yourself? If it's working for you we can close the issue.

**Comment by uqzhaozicheng** [comment]
Yes. It works well now! Great thanks!
